In [ ]:
# Data Manipulation
#Use broadcasting to normalize a 2D numpy array row-wise.

In [1]:
import numpy as np

array = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

row_sums = array.sum(axis=1, keepdims=True)

normalized_array = array / row_sums

print("Original Array:\n", array)
print("\nRow-wise Normalized Array (by sum):\n", normalized_array)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Row-wise Normalized Array (by sum):
 [[0.16666667 0.33333333 0.5       ]
 [0.26666667 0.33333333 0.4       ]
 [0.29166667 0.33333333 0.375     ]]


In [2]:
## Normalizing by eucliedian norm 
row_norms = np.linalg.norm(array, axis=1, keepdims=True)

normalized_by_norm = array / row_norms

print("\nRow-wise Normalized Array (by L2 norm):\n", normalized_by_norm)



Row-wise Normalized Array (by L2 norm):
 [[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]
 [0.50257071 0.57436653 0.64616234]]
